# Generated by Django 4.2.9 on 2024-01-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=50)),
                ('Mother_Name', models.CharField(max_length=50)),
                ('Adhar_No', models.IntegerField()),
                ('Contact_No', models.ImageField(upload_to='')),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
