# Generated by Django 4.2.8 on 2024-01-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=50)),
                ('Teacher_Name', models.CharField(max_length=50)),
                ('Mother_Name', models.CharField(max_length=50)),
                ('Adhar_No', models.IntegerField(max_length=50)),
                ('Contact_No', models.IntegerField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Salary', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
