# Generated by Django 4.2.8 on 2024-01-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_subject_alter_student_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Teacher_Name',
            field=models.CharField(max_length=50),
        ),
    ]
