# Generated by Django 4.2.8 on 2024-01-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_student_teacher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Name', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=40)),
                ('Contact_No', models.IntegerField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Adhar_No', models.IntegerField(max_length=50)),
                ('Salary', models.IntegerField(default=10000, max_length=50)),
            ],
        ),
    ]
