# Generated by Django 4.2.8 on 2024-01-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Adhar_No',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Salary',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Contact_No',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_Name',
            field=models.CharField(max_length=40),
        ),
    ]
